### ISSUE TITLE
Error while using conan package

### ISSUE THREAD

**Issue by MojaveWastelander** [lasote/conan-libpng#1]
I need libpng for another package, but when I tried to use it I got an error:

>   File <frozen importlib._bootstrap>, line 693, in _load
> ...
>   File "C:\Users\user\.conan\data\libpng\1.6.21\lasote\ci\export\conanfile.py", line 52
>     self.run(configure)
>                       ^
> TabError: inconsistent use of tabs and spaces in indentation

There is a tab on line 52.
Another issue is that version 1.6.21 is moved to [older-releases](https://sourceforge.net/projects/libpng/files/libpng16/older-releases/).

**Comment by lasote** [comment]
Thanks for telling. I'll try to upload the 1.6.23 version and fix the 1.6.21 during the day

**Comment by lasote** [comment]
Hi, 1.6.21 should be OK now. Tell me if it works. 1.6.23 will need some time.

**Comment by lasote** [comment]
1.6.23 is also ready! Please, open this issue is something goes wrong.

**Comment by MojaveWastelander** [comment]
Both build as expected, no problems encountered.
